export const CHANHGE_LOGIN_FORM = 'CHANHGE_LOGIN_FORM'
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM'
export const SET_SHOW_LOGIN = 'SET_SHOW_LOGIN'

export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'
export const UPDATE_LOGGED_IN = 'UPDATE_LOGGED_IN'

export const UPDATE_TOKEN = 'UPDATE_TOKEN'

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING'
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS'
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED'
